default_platform(:ios)

platform :ios do
  desc "Build the iOS app for a specific flavor."
  lane :build do |options|
    flavor = options[:flavor]
    flutter_build(
      platform: 'ios',
      flavor: flavor,
      build_name: ENV['BUILD_NAME'],
      build_number: ENV['BUILD_NUMBER']
    )
  end
end
