// Parts of this file is generated by FlutterFire CLI
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Global variable that holds the current flavor, initialized in main.dart
String appFlavor = 'dev'; // Default value

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        switch (appFlavor) {
          case 'dev':
            return androidDev;
          case 'qa':
            return androidQA;
          case 'staging':
            return androidStaging;
          case 'prod':
            return androidProd;
          default:
            throw Exception('Unknown Android flavor: $appFlavor');
        }
      case TargetPlatform.iOS:
        switch (appFlavor) {
          case 'dev':
            return iosDev;
          case 'qa':
            return iosQA;
          case 'staging':
            return iosStaging;
          case 'prod':
            return iosProd;
          default:
            throw Exception('Unknown iOS flavor: $appFlavor');
        }
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // DEV ENVIRONMENT - Already defined in your code
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCkLCew9UiNoTydGg2L8PhVcPsaZUs9dsc',
    appId: '1:727282540846:android:d0b82567c73a614c561abf',
    messagingSenderId: '727282540846',
    projectId: 'petrasoft-dev-fad85',
    storageBucket: 'petrasoft-dev-fad85.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyBmEmQFIBS0ScuxTzKfpiTmqJXLlz4aO9k',
    appId: '1:727282540846:ios:50e50befb6adad05561abf',
    messagingSenderId: '727282540846',
    projectId: 'petrasoft-dev-fad85',
    storageBucket: 'petrasoft-dev-fad85.firebasestorage.app',
    iosBundleId: 'com.petrasoftsolutions.mobile.dev',
  );

  // QA ENVIRONMENT
  static const FirebaseOptions androidQA = FirebaseOptions(
    apiKey: 'AIzaSyD2jip2B6rxuK11t87Itr1Xztx-bqvPGLg',
    appId: '1:1051869953939:android:8fcba8b386ab6b567b7266',
    messagingSenderId: '1051869953939',
    projectId: 'petrasoft-qa',
    storageBucket: 'petrasoft-qa.firebasestorage.app',
  );

  static const FirebaseOptions iosQA = FirebaseOptions(
    apiKey: 'AIzaSyCi_lZ8FJ-OQukc3R9MV-2THUIvNKbk_dY',
    appId: '1:1051869953939:ios:5e546444ecb98bd37b7266',
    messagingSenderId: '1051869953939',
    projectId: 'petrasoft-qa',
    storageBucket: 'petrasoft-qa.firebasestorage.app',
    iosBundleId: 'com.petrasoftsolutions.mobile.qa',
  );

  // STAGING ENVIRONMENT
  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyDtivW3HLtZC4yNh-I1beFAl53VTLfQuoo',
    appId: '1:775235070455:android:1139ea73c963cab286a6f2',
    messagingSenderId: '775235070455',
    projectId: 'petrasoft-staging',
    storageBucket: 'petrasoft-staging.firebasestorage.app',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyBAakMPtkgM_RaHbGCvQhRk3cV3tsQKZMA',
    appId: '1:775235070455:ios:bff82caa8481fed286a6f2',
    messagingSenderId: '775235070455',
    projectId: 'petrasoft-staging',
    storageBucket: 'petrasoft-staging.firebasestorage.app',
    iosBundleId: 'com.petrasoftsolutions.mobile.staging',
  );

  // PROD ENVIRONMENT
  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyC-EpkwLXzfy2oZPxiiXZZlD_HETv9yetU',
    appId: '1:465049471348:android:745d46079230ea51ac4421',
    messagingSenderId: '465049471348',
    projectId: 'petrasoft-prod',
    storageBucket: 'petrasoft-prod.firebasestorage.app',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyA4uQD8fJV2r3tn82KcXNvuOo8rRx0F07M',
    appId: '1:465049471348:ios:745d46079230ea51ac4421',
    messagingSenderId: '465049471348',
    projectId: 'petrasoft-prod',
    storageBucket: 'petrasoft-prod.firebasestorage.app',
    iosBundleId: 'com.petrasoftsolutions.mobile.prod',
  );
}
