default_platform(:android)

platform :android do
  desc "Build the Android app for a specific flavor (signed release)"
  lane :build do |options|
    flavor = options[:flavor]
    
    # Build signed release AAB with split debug info
    gradle(
      task: 'bundle',
      flavor: flavor,
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_FILE'],
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )
    
    # Also generate mapping.txt for ProGuard/R8 (crash symbolication)
    # The mapping file will be in app/build/outputs/mapping/<flavor>Release/mapping.txt
  end

  desc "Upload Android app to Google Play (Internal track for non-prod)"
  lane :upload do |options|
    flavor = options[:flavor]
    
    # Determine track based on flavor
    track = flavor == 'prod' ? 'production' : 'internal'
    
    # Set up service account JSON
    service_account_json = if flavor == 'prod'
      ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PROD']
    elsif flavor == 'staging'
      ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_STAGING']
    elsif flavor == 'qa'
      ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_QA']
    else
      nil
    end
    
    if service_account_json.nil?
      UI.user_error!("No service account JSON found for flavor: #{flavor}")
    end
    
    # Write JSON to temp file
    json_key_file = "/tmp/play-service-account-#{flavor}.json"
    File.write(json_key_file, service_account_json)
    
    # Locate AAB and mapping artifacts dynamically (works across AGP/Flutter variations)
    aab_globs = [
      "app/build/outputs/bundle/#{flavor}Release/*.aab",
      "app/build/outputs/bundle/**/#{flavor}Release/*.aab",
      "app/build/outputs/bundle/**/*#{flavor}*.aab",
    ]

    aab_path = nil
    aab_globs.each do |g|
      found = Dir.glob(g).select { |p| File.file?(p) }.first
      if found
        aab_path = found
        break
      end
    end

    unless aab_path && File.exist?(aab_path)
      UI.user_error!("Could not find AAB for flavor '#{flavor}'. Searched globs: #{aab_globs.join(', ')}")
    end

    # Locate mapping file (optional)
    mapping_path = Dir.glob("app/build/outputs/mapping/**/#{flavor}Release/mapping*.txt").select { |p| File.file?(p) }.first

    upload_to_play_store(
      package_name: "com.petrasoftsolutions.mobile.#{flavor}",
      track: track,
      aab: aab_path,
      json_key: json_key_file,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      mapping: mapping_path
    )
    
    # Clean up temp file
    File.delete(json_key_file) if File.exist?(json_key_file)
  end

  desc "Build and upload Android app"
  lane :build_and_upload do |options|
    build(options)
    upload(options)
  end
end
